name: clean_architecture_flutter
description: A new Flutter project with clean architecture.

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  shared_preferences: ^2.1.1
  connectivity_plus: ^4.0.2
  get_it: ^7.6.4
  dartz: ^0.10.1
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dio: ^5.3.3
  formz: ^0.6.1
  go_router: ^11.0.0
  mime: ^1.0.4
  file_picker: ^5.5.0
dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

  uses-material-design: true
